name = "ValueGraphFromDataFrame"
uuid = "8b51dcbb-633b-449d-8b9f-ef904d1a718d"
authors = ["Jakob Hoffmann <jfb-hoffmann@hotmail.de> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
SimpleValueGraphs = "b43c691f-cac2-5415-8122-396fe16a49fc"

[compat]
LightGraphs = "1.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
